version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    ports:
      - ${POSTGRES_PORT}:5432
  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - 16686:16686
      - 55680:55680
      - 55681:55681
